spring.application.name=studentjob

spring.datasource.url=jdbc:postgresql://localhost:5432/springdb
spring.datasource.username=azus
spring.datasource.password=01112006Lam@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true